Repository vferat/pycrostates, pull requests merged in 2022-11, with the labels that each got.

#90 [DOC] Add BibClean to format references.bib
  .github/workflows/code-style.yml
  docs/references.bib
  pyproject.toml
Labels: 📓 doc

#92 [ENH] Add support for AAHC clustering
  docs/references.bib
  docs/source/api/cluster.rst
  docs/source/dev/changes/latest.rst
  docs/source/dev/changes/names.inc
  pycrostates/cluster/__init__.py
  pycrostates/cluster/_base.py
  pycrostates/cluster/aahc.py
  pycrostates/cluster/kmeans.py
  pycrostates/cluster/tests/test_aahc.py
  pycrostates/html_templates/repr/AAHCluster.html.jinja
  pycrostates/io/fiff.py
Labels: 🌟 enhancement, clustering

#91 Add transition probabilities
  .github/workflows/draft-pdf.yml
  docs/source/api/segmentation.rst
  docs/source/conf.py
  docs/source/dev/changes/latest.rst
  pycrostates/cluster/_base.py
  pycrostates/segmentation/__init__.py
  pycrostates/segmentation/_base.py
  pycrostates/segmentation/segmentation.py
  pycrostates/segmentation/tests/test_segmentation.py
  pycrostates/segmentation/tests/test_transitions.py
  pycrostates/segmentation/transitions.py
  pycrostates/tests/__init__.py
  pycrostates/utils/_docs.py
  pycrostates/utils/tests/test_config.py
  pycrostates/viz/cluster_centers.py
  pyproject.toml
  tutorials/cluster/00_modK.py
  tutorials/cluster/10_subject_level_with_resampling.py
  tutorials/cluster/README.rst
  tutorials/group_level_analysis/00_group_level_with_individual_clusters.py
  tutorials/group_level_analysis/10_group_level_with_individual_gfp_peaks.py
  tutorials/metrics/00_metrics.py
  tutorials/preprocessing/00_extract_gfp_peaks.py
  tutorials/preprocessing/10_resampling.py
  tutorials/segmentation/00_segmentation.py
  tutorials/segmentation/README.rst
Labels: 🌟 enhancement, dependencies
